### ISSUE TITLE
Добавь хоть скриншот (Add screenshot)

### ISSUE THREAD

**Issue by Shemplo** [guapstudent1/DragFigureGL#1]
Лень компилить, OGL интерпретатор в голове не держу, но посмотреть хочется
(I'm to lazy to compile and don't have OGL interpreter in head but wanna see runtime)

**Comment by guapstudent1** [comment]
В архиве релиз версия. За основу взят урок от Nehe и допилен под свои нужды. У меня разрешение ноута: 1366x768 возможно на мелком будут ждать сюрпризы. Не тестил.

Отпишись, как запустишь!
[DragFigureGL.zip](https://github.com/guapstudent1/DragFigureGL/files/4000569/DragFigureGL.zip)

И скорее всего нужно нажать в свойствах разблокировать :)

**Comment by guapstudent1** [comment]
А потом я нашел куда плюхнуть релиз

**Comment by Shemplo** [comment]
Хорошо, посмотрю в ближайшее время

**Comment by Shemplo** [comment]
Я посмотрел, норм
